### ISSUE TITLE
Automatic reconnect fails after TCP package processing error

### ISSUE THREAD

**Issue by Yspadadden** [msemys/esjc#28] opened 2017-09-20 15:20 UTC
When there is an exception in the TCP processing (f.e. TooLongFrameException) the library reports the error (good), disconnects (bad), and starts a reconnect (good). Unfortunately the reconnect fails because the connection is still seen as open for some reason. 

Here's some relevant logs: 

> [esio-1-2] ERROR com.github.msemys.esjc.EventStore - Error when processing TCP package
> io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 67108864: 139816238 - discarded
> 	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:498)
> <snip>
> [esio-1-2] INFO com.github.msemys.esjc.EventStore - Connection to [localhost/127.0.0.1:1123, L/127.0.0.1:59473] closed.
> [esio-1-2] INFO com.github.msemys.esjc.EventStore - Disconnected, reason: Error when processing TCP package
> [es-1-2] ERROR com.github.msemys.esjc.EventStore - Unable to connect: Connection [id: 0x785fb717, L:/127.0.0.1:59473 ! R:localhost/127.0.0.1:1123] is already active.

This prevents a graceful retry with a smaller batch size. Please find attached an example project that reproduces the error and attempts a retry. The retry fails because the connection is closed. 

[esjc-tests.zip](https://github.com/msemys/esjc/files/1318215/esjc-tests.zip)

**Comment by Yspadadden** [comment] 2017-09-21 09:07
Figured out what the issue is, and how to work around it. The problem is, that I retry immediately when getting the result. This happens on the esjc thread responsible for handling the error which is also the thread that will ultimately close the connection via async await (closeTcpConnection() in EventStoreTcp.java:764). 

Requesting a new (smaller) batch enqueues a new job in the worker queue. The enqueue method has the side effect that it starts a new connection when the current connection appears to be disconnected (based on isRunning()). This happens before the connection is completely closed causing the reconnect error. 

The workaround is to wait for the ConnectionClosed clientEvent via addListener(...) and only retry after the connection is completely closed. 

I am not sure what to make of this. It feels kind of bugged. Probably the result of the batch read should only arrive at the client when the connection has been properly disposed of. But I am not sure, if you even have enough control over that with all the queues and pipelines involved. Please feel free to close this issue, if you don't see this as a bug that needs fixing.

**Comment by Yspadadden** [comment] 2017-09-22 11:32
For reference. I opened an issue regarding the 64 MB limit in the eventstore project [here](https://github.com/EventStore/EventStore/issues/1437).

**Comment by msemys** [comment] 2017-09-24 14:18
I think the problem is on the client side error handling when connection (to single node es server) is lost while client reads the message from server. 
At the moment the client will always disconnects if any unexpected error occurs on tcp channel.

ps.: #29 is related

**Comment by ontehfritz** [comment] 2018-07-24 19:13
Is this fixed? I think  I may be running into the same issue with volatile subscription to a stream, it seems to not receive events after an n period of time, don't know if its a time out, or a tcp error.

**Comment by msemys** [comment] 2019-03-10 12:35
fixed in #44

**Closed by msemys** 2019-03-10 12:35 UTC
Labels: bug
